trigger:
  - chrpap-sf1-abuild

variables:
  DotNetCoreVersion: '2.1.503'
  
jobs:
  - job: Ubuntu_Build
    pool:
      vmImage: 'ubuntu-16.04'
  
    steps:
        - task: DotNetCoreInstaller@0
          displayName: 'Use .NET Core sdk $(DotNetCoreVersion)'
          inputs:
            version: '$(DotNetCoreVersion)'
        - script: './testsf_on_linux.sh'
          displayName: 'Build and test on Non-windows machine'
        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: '**/*.trx'
            testRunTitle: 'Ubuntu Test Results'
            testResultsFormat: 'VSTest'
            mergeTestResults: true